SPRITE nx01 "sprite/nx01.png" 3 2 BEST
SPRITE bulletVulcan "sprite/bullet_vulcan.png" 1 1 BEST
SPRITE bulletLaser "sprite/laser.png" 1 1 BEST
SPRITE bulletLaserBig "sprite/laser_big.png" 2 1 BEST
SPRITE bulletWide "sprite/wide.png" 1 1 BEST
SPRITE bulletHoming "sprite/homing.png" 1 1 BEST
SPRITE bulletFlame "sprite/flame.png" 1 1 BEST
SPRITE enemyDrone "sprite/enemy_drone.png" 1 1 BEST
SPRITE enemyFighter "sprite/enemy_fighter.png" 1 1 BEST
SPRITE enemyBomber "sprite/enemy_bomber.png" 2 2 BEST
SPRITE enemyTurret "sprite/enemy_turret.png" 1 1 BEST
SPRITE enemySwarm "sprite/enemy_swarm.png" 1 1 BEST
SPRITE enemyCharger "sprite/enemy_charger.png" 1 1 BEST
SPRITE enemyShield "sprite/enemy_shield.png" 1 1 BEST
SPRITE enemyBullet "sprite/enemy_bullet.png" 1 1 BEST
SPRITE powerupLaser "sprite/powerup_laser.png" 1 1 BEST
SPRITE powerupWide "sprite/powerup_wide.png" 1 1 BEST
SPRITE powerupHoming "sprite/powerup_homing.png" 1 1 BEST
SPRITE powerupFlame "sprite/powerup_flame.png" 1 1 BEST
SPRITE powerupP "sprite/powerup_p.png" 1 1 BEST
SPRITE powerupBomb "sprite/powerup_bomb.png" 1 1 BEST
SPRITE powerupSpeed "sprite/powerup_speed.png" 1 1 BEST
SPRITE powerup1up "sprite/powerup_1up.png" 1 1 BEST
